export const TITLE_LENGTH_MAX = 64;
export const INTERVAL_DEFAULT = 0.25;
export const INTERVAL_MIN = 0.1;
export const INTERVAL_MAX = 1;
export const NOTES_COUNT_MAX = 1000;
export const NOTE_SIZE = 20;
export const MINI_NOTE_SIZE = 10;
export const CHART_WIDTH_DEFAULT = 128;
export const CHART_WIDTH_DELTA = 32;
export const CHART_WIDTH_MAX = 640;
export const CHART_HEIGHT = 48;
export const FREQUENCY_BASE = 130.81; // C3
